title: Nnamdi Williams David
logo: headshot.jpg
description: Data Analyst with over three years experience working across different sectors using statistical tools such as SSIS, Advanced Excel for report automation, SQL for data manipulation and Power BI for creating business intelligence reports
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
